/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteAboutRouteImport } from './routes/_site.about'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteFundingRouteImport } from './routes/_site.funding'
import { Route as SiteHowItWorksRouteImport } from './routes/_site.how-it-works'
import { Route as SitePlatformRouteImport } from './routes/_site.platform'
import { Route as SitePrivacyPolicyRouteImport } from './routes/_site.privacy-policy'
import { Route as SiteSecurityRouteImport } from './routes/_site.security'
import { Route as SiteTermsOfUseRouteImport } from './routes/_site.terms-of-use'
import { Route as SiteThankYouRouteImport } from './routes/_site.thank-you'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFundingRoute = SiteFundingRouteImport.update({
  id: '/funding',
  path: '/funding',
  getParentRoute: () => SiteRoute,
} as any)
const SiteHowItWorksRoute = SiteHowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => SiteRoute,
} as any)
const SitePlatformRoute = SitePlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => SiteRoute,
} as any)
const SitePrivacyPolicyRoute = SitePrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSecurityRoute = SiteSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTermsOfUseRoute = SiteTermsOfUseRouteImport.update({
  id: '/terms-of-use',
  path: '/terms-of-use',
  getParentRoute: () => SiteRoute,
} as any)
const SiteThankYouRoute = SiteThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/funding': typeof SiteFundingRoute
  '/how-it-works': typeof SiteHowItWorksRoute
  '/platform': typeof SitePlatformRoute
  '/privacy-policy': typeof SitePrivacyPolicyRoute
  '/security': typeof SiteSecurityRoute
  '/terms-of-use': typeof SiteTermsOfUseRoute
  '/thank-you': typeof SiteThankYouRoute
}
export interface FileRoutesByTo {
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/funding': typeof SiteFundingRoute
  '/how-it-works': typeof SiteHowItWorksRoute
  '/platform': typeof SitePlatformRoute
  '/privacy-policy': typeof SitePrivacyPolicyRoute
  '/security': typeof SiteSecurityRoute
  '/terms-of-use': typeof SiteTermsOfUseRoute
  '/thank-you': typeof SiteThankYouRoute
  '/': typeof SiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/about': typeof SiteAboutRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/funding': typeof SiteFundingRoute
  '/_site/how-it-works': typeof SiteHowItWorksRoute
  '/_site/platform': typeof SitePlatformRoute
  '/_site/privacy-policy': typeof SitePrivacyPolicyRoute
  '/_site/security': typeof SiteSecurityRoute
  '/_site/terms-of-use': typeof SiteTermsOfUseRoute
  '/_site/thank-you': typeof SiteThankYouRoute
  '/_site/': typeof SiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/funding'
    | '/how-it-works'
    | '/platform'
    | '/privacy-policy'
    | '/security'
    | '/terms-of-use'
    | '/thank-you'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/contact'
    | '/funding'
    | '/how-it-works'
    | '/platform'
    | '/privacy-policy'
    | '/security'
    | '/terms-of-use'
    | '/thank-you'
    | '/'
  id:
    | '__root__'
    | '/_site'
    | '/_site/about'
    | '/_site/contact'
    | '/_site/funding'
    | '/_site/how-it-works'
    | '/_site/platform'
    | '/_site/privacy-policy'
    | '/_site/security'
    | '/_site/terms-of-use'
    | '/_site/thank-you'
    | '/_site/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/funding': {
      id: '/_site/funding'
      path: '/funding'
      fullPath: '/funding'
      preLoaderRoute: typeof SiteFundingRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/how-it-works': {
      id: '/_site/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof SiteHowItWorksRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/platform': {
      id: '/_site/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof SitePlatformRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/privacy-policy': {
      id: '/_site/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof SitePrivacyPolicyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/security': {
      id: '/_site/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SiteSecurityRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/terms-of-use': {
      id: '/_site/terms-of-use'
      path: '/terms-of-use'
      fullPath: '/terms-of-use'
      preLoaderRoute: typeof SiteTermsOfUseRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/thank-you': {
      id: '/_site/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof SiteThankYouRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteFundingRoute: typeof SiteFundingRoute
  SiteHowItWorksRoute: typeof SiteHowItWorksRoute
  SitePlatformRoute: typeof SitePlatformRoute
  SitePrivacyPolicyRoute: typeof SitePrivacyPolicyRoute
  SiteSecurityRoute: typeof SiteSecurityRoute
  SiteTermsOfUseRoute: typeof SiteTermsOfUseRoute
  SiteThankYouRoute: typeof SiteThankYouRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteContactRoute: SiteContactRoute,
  SiteFundingRoute: SiteFundingRoute,
  SiteHowItWorksRoute: SiteHowItWorksRoute,
  SitePlatformRoute: SitePlatformRoute,
  SitePrivacyPolicyRoute: SitePrivacyPolicyRoute,
  SiteSecurityRoute: SiteSecurityRoute,
  SiteTermsOfUseRoute: SiteTermsOfUseRoute,
  SiteThankYouRoute: SiteThankYouRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
